name: flutter_bloc_event_bus
description: "Event-driven communication between components built on top of flutter_bloc"
version: 1.0.1
repository: https://github.com/salihagic/flutter_bloc_event_bus

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
