name: flutter_bloc_event_bus
description: "Event-driven communication between components built on top of flutter_bloc"
version: 0.0.1
repository: https://github.com/salihagic/flutter_bloc_event_bus

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
